version: '3.9'
services:
  db:
    container_name: db
    image: postgres:15.2
    volumes:
      - dbvolume:/var/lib/postgresql/dbvolume
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USERS_DB: users_service_database
      POSTGRES_BILL_DB: bill_service_database
      POSTGRES_DEPOSIT_DB: deposit_service_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    deploy:
      restart_policy:
        condition: on-failure


  config-service:
    container_name: config-service
    build: config-service
    ports:
      - 8001:8001
    depends_on:
      - db

  discovery-server:
    container_name: discovery-server
    restart: always
    build: discovery-server
    ports:
      - 8761:8761
    depends_on:
      - config-service

  gateway:
    container_name: gateway
    restart: always
    build: gateway
    ports:
      - 8989:8989
    depends_on:
      - config-service
      - discovery-server

  user-service:
    restart: on-failure
    container_name: user-service
    build: user-service
    ports:
      - 8081:8081
    depends_on:
      - config-service
      - discovery-server

  bill-service:
    restart: on-failure
    container_name: bill-service
    build: bill-service
    ports:
      - 8082:8082
    depends_on:
      - config-service
      - discovery-server

  deposit-service:
    restart: on-failure
    container_name: deposit-service
    build: deposit-service
    ports:
      - 8080:8080
    depends_on:
      - config-service
      - discovery-server

  notification-service:
    restart: on-failure
    container_name: notification-service
    build: notification-service
    ports:
      - 9999:9999
    depends_on:
      - config-service
      - discovery-server

  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: rabbitmq
    labels:
      NAME: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    depends_on:
      - config-service
      - discovery-server
      - user-service

volumes:
  dbvolume: