hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

spring:
  cloud:
    gateway:
      routes:
        user-service:
          path: /users/**
          serviceId: user-service
          stripPrefix: false

        bill-service:
          path: /bills/**
          serviceId: bill-service
          stripPrefix: false

        deposit-service:
          path: /deposits/**
          serviceId: deposit-service
          stripPrefix: false

server:
  port: 8989