hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

cloud:
  user-url: http://user-service:8081
  bill-url: http://bill-service:8082
  deposit-url: http://deposit-service:8080

spring:
  cloud:
    gateway:
#      default-filters:
#        - TokenRelay
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: ${cloud.user-url}
          predicates:
            - Path=/users/**

        - id: bill-service
          uri: ${cloud.bill-url}
          predicates:
            - Path=/bills/**

        - id: deposit-service
          uri: ${cloud.deposit-url}
          predicates:
            - Path=/deposits/**



#        user-service:
#          path: /users/**
#          serviceId: user-service
#          stripPrefix: false
#
#        bill-service:
#          path: /bills/**
#          serviceId: bill-service
#          stripPrefix: false
#
#        deposit-service:
#          path: /deposits/**
#          serviceId: deposit-service
#          stripPrefix: false

server:
  port: 8989